#define PROJECT_CONF_H_
#define RF_CORE_CONF_CHANNEL 15
#define NETSTACK_CONF_RDC_CHANNEL_CHECK_RATE 32
#define NETSTACK_NETWORK rime_driver
#define NETSTACK_CONF_MAC csma_driver
#define NETSTACK_CONF_RDC nullrdc_driver
#define NETSTACK_CONF_FRAMER framer_802154
